version: '3.7'
services:
  react:
    container_name: 'react-prod'
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3002:80'
    environment:
      - NODE_ENV=development